spring.application.name=Vox
#spring.profiles.active=basic
spring.profiles.active=jwt
spring.datasource.name=db_vox
spring.datasource.base.url=jdbc:postgresql://localhost:5432/
spring.datasource.url=jdbc:postgresql://localhost:5432/${spring.datasource.name}
spring.datasource.username=postgres
spring.datasource.password=123456
logging.level.org.springframework.security=TRACE
cloudinary.cloud-name=dohegns1y
cloudinary.api-key=384825531979271
cloudinary.api-secret=3MXFoEtxQd_MMWxDkk5C1mKlgcI