spring.application.name=Vox
#spring.profiles.active=basic
spring.profiles.active=jwt
spring.datasource.name=db_vox
spring.datasource.base.url=jdbc:postgresql://localhost:5432/
spring.datasource.url=jdbc:postgresql://localhost:5432/${spring.datasource.name}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
logging.level.org.springframework.security=TRACE

# SMTP
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true