spring.application.name=Vox-backend-jwt
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

livekit.api-key=${LIVEKIT_API_KEY}
livekit.api-secret=${LIVEKIT_API_SECRET}
livekit.url=${LIVEKIT_URL}

app.mail.from=${MAIL_FROM}
app.frontend.reset-password-url=${FRONTEND_RESET_URL}