import { Routes } from '@angular/router';
import { LoginComponent } from './pages/login/login.component';
import { ProjetosComponent } from './pages/projetos/projetos.component';
import { ProjetoDetalheComponent } from './pages/projeto-detalhe/projeto-detalhe.component';
import { SugestoesComponent } from './pages/sugestoes/sugestoes.component';
import { RelatarProblemaComponent } from './pages/relatar-problema/relatar-problema.component';
import { ModeracaoComponent } from './pages/moderacao/moderacao.component';
import { ComunidadeComponent } from './pages/comunidade/comunidade.component';
import { PerfilComponent } from './pages/perfil/perfil.component';
import { AudienciaComponent } from './pages/audiencia/audiencia.component';
import { AudienciaSalaComponent } from './pages/audiencia-sala/audiencia-sala.component';
import { ConfiguracoesComponent } from './pages/configuracoes/configuracoes.component';
import { CadastroComponent } from './pages/cadastro/cadastro.component';
import { ProblemasComponent } from './pages/problemas/problemas.component';
import { ProblemaDetalheComponent } from './pages/problema-detalhe/problema-detalhe.component';
import { DashboardComponent } from './pages/dashboard/dashboard.component';
import { LogsComponent } from './pages/logs/logs.component';
import { UsuariosComponent } from './pages/usuarios/usuarios.component';

export const routes: Routes = [
  { path: '', redirectTo: 'projetos', pathMatch: 'full' },
  { path: 'login', component: LoginComponent },
  { path: 'cadastro', component: CadastroComponent },
  { path: 'projetos', component: ProjetosComponent },
  { path: 'projetos/:id', component: ProjetoDetalheComponent },
  { path: 'sugestoes', component: SugestoesComponent },
  { path: 'relatar-problema', component: RelatarProblemaComponent },
  { path: 'problemas', component: ProblemasComponent },
  { path: 'problemas/:id', component: ProblemaDetalheComponent },
  { path: 'moderacao', component: ModeracaoComponent },
  { path: 'comunidade', component: ComunidadeComponent },
  { path: 'perfil', component: PerfilComponent },
  { path: 'audiencia', component: AudienciaComponent },
  { path: 'audiencia/:id', component: AudienciaSalaComponent },
  { path: 'configuracoes', component: ConfiguracoesComponent },
  { path: 'dashboard', component: DashboardComponent },
  { path: 'logs', component: LogsComponent },
  { path: 'usuarios', component: UsuariosComponent },
  { path: '**', redirectTo: 'projetos' }
];
